name: Check and Configure Repository Labels
run-name: "#${{ github.event.issue.number }}"
permissions:
  issues: write
on:
  issues:
    types: [ opened ]
  workflow_dispatch:
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels in repository
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredLabels = [ 'major', 'minor', 'patch' ]
            
            const { data: labels } = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            
            const existingLabels = labels.map(label => label.name)
            const missingLabels = requiredLabels.filter(label => !existingLabels.includes(label))
            
            if (missingLabels.length > 0) {
              const commentBody = `> [!WARNING]
            > Missing required labels: ${missingLabels.join(', ')}
            
            > [!TIP]
            > You can add these labels manually, or type \`/configure-default-labels\` to automatically configure them.`

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              })
              console.log(`::warning::Missing required labels: ${missingLabels.join(', ')}`)
            }
