name: E2E Tests
run-name: >
  E2E Tests - Commit: ${{ github.event.head_commit && github.event.head_commit.message ? split(github.event.head_commit.message, '\n')[0] : 'No commit message' }}
on:
  push: { }
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run E2E Tests
        run: npm run test:e2e
